[build]
  cmd = "pip install --no-cache-dir -r requirements.txt"

[start]
  cmd = "cd bdpricegear-backend && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --timeout 300 --workers 2"

[variables]
  PYTHONPATH = "/app/bdpricegear-backend"